export const GET_ALL_VOUCHERS = "GET_ALL_VOUCHERS";
export const GET_ALL_VOUCHERS_SUCCESS = "GET_ALL_VOUCHERS_SUCCESS";
export const GET_ALL_VOUCHERS_FAILED = "GET_ALL_VOUCHERS_FAILED";

export const GET_VOUCHER = "GET_VOUCHER";
export const GET_VOUCHER_SUCCESS = "GET_VOUCHER_SUCCESS";
export const GET_VOUCHER_FAILED = "GET_VOUCHER_FAILED";

export const ADD_VOUCHER = "ADD_VOUCHER";
export const ADD_VOUCHER_SUCCESS = "ADD_VOUCHER_SUCCESS";
export const ADD_VOUCHER_FAILED = "ADD_VOUCHER_FAILED";

export const UPDATE_VOUCHER = "UPDATE_VOUCHER";
export const UPDATE_VOUCHER_SUCCESS = "UPDATE_VOUCHER_SUCCESS";
export const UPDATE_VOUCHER_FAILED = "UPDATE_VOUCHER_FAILED";

export const DELETE_VOUCHER = "DELETE_VOUCHER";
export const DELETE_VOUCHER_SUCCESS = "DELETE_VOUCHER_SUCCESS";
export const DELETE_VOUCHER_FAILED = "DELETE_VOUCHER_FAILED";

export const SEARCH_VOUCHER = "SEARCH_VOUCHER";
export const SEARCH_VOUCHER_SUCCESS = "SEARCH_VOUCHER_SUCCESS";
export const SEARCH_VOUCHER_FAILED = "SEARCH_VOUCHER_FAILED";
